coll: nb_pm_tasks
blocks:
  - key: filter
    type: filterForm
    coll: nb_pm_tasks
    fields:
      - field: title
        label: 搜索
        filterPaths:
          - title
          - task_no
          - assignee
      - status
      - priority
      - project
      - assignee
    actions:
      - submit
      - reset
    field_layout:
      - - title
      - - status
        - priority
        - project
      - - assignee
  - key: table
    type: table
    coll: nb_pm_tasks
    fields:
      - field: title
        clickToOpen: true
      - task_no
      - project
      - assignee
      - due_date
      - planned_hours
      - actual_hours
      - status
    actions:
      - filter
      - refresh
      - addNew
      - export
    recordActions:
      - edit
      - view
      - delete
layout:
  - - filter
  - - table
