- title: 项目管理
  type: group
  icon: projectoutlined
  children:
    - title: Projects
      icon: projectoutlined
    - title: Tasks
      icon: profileoutlined
    - title: Milestones
      icon: flagoutlined
    - title: Members
      icon: teamoutlined
